# -*- coding: utf-8 -*-
from google.appengine.ext import ndb

from datetime import datetime

userFixtures = [{'userEmail': 'user@mail.com',
                'userName': 'John Doe',
                'userSkill': ['Python', 'Communication', 'Leadership'],
                'userTag': ['DTU', 'Digital Media Engineering', 'Android'],
                 },
                {'userEmail': 'rating.user@mail.com',
                 'userName': 'Jane Doe',
                 },
                ]
ratingFixtures = [{'userEmail': userFixtures[0]['userEmail'],
                   'ratingUserEmail': userFixtures[1]['userEmail'],
                   'ratingValue': 5,
                   },
                  ]

huddleFixtures = [{'huddleDateAndTime': datetime.now(),
                   'huddleLocation': ndb.GeoPt('55.785061,12.519927'),
                   'huddleAdmin': 'user@mail.com',
                   'huddleName': 'Mobile Prototyping',
                   'huddleTags': ['DTU', '02728', 'Digital Media Engineering'],
                   'huddleUser': ['user@mail.com', 'tester@mail.com'],
                   },
                  ]

groupFixtures = [{'huddleName': 'Mobile Prototyping',
                  'groupName': 'Group 1',
                  'groupUser': ['user@mail.com', 'tester@mail.com'],
                  'groupAdmin': 'user@mail.com',
                  },
                 ]

appointmentFixtures = [{'huddleName': groupFixtures[0]['huddleName'],
                        'groupName': groupFixtures[0]['groupName'],
                        'appointmentName': 'Hangout',
                        'appointmentTime': datetime(2014,4,9,9,0,0),
                        },
                       ]

chatFixtures = [{'huddleName': groupFixtures[0]['huddleName'],
                 'groupName': groupFixtures[0]['groupName'],
                 'timestamp': datetime(2014,4,1,13,0,0),
                 'text':'Hi!',
                 'author': 'user@mail.com',
                 },
                {'huddleName': groupFixtures[0]['huddleName'],
                 'groupName': groupFixtures[0]['groupName'],
                 'timestamp': datetime(2014,4,1,13,0,10),
                 'text':'Hello!',
                 'author': 'tester@mail.com',
                 },
                {'huddleName': groupFixtures[0]['huddleName'],
                 'groupName': groupFixtures[0]['groupName'],
                 'timestamp': datetime(2014,4,1,13,0,15),
                 'text':'Whats up?',
                 'author': 'user@mail.com',
                 },
                {'huddleName': groupFixtures[0]['huddleName'],
                 'groupName': groupFixtures[0]['groupName'],
                 'timestamp': datetime(2014,4,1,13,0,25),
                 'text':'Nothing special',
                 'author': 'tester@mail.com',
                 },
                {'huddleName': groupFixtures[0]['huddleName'],
                 'groupName': groupFixtures[0]['groupName'],
                 'timestamp': datetime(2014,4,1,13,0,30),
                 'text':'Ok, I was just wondering when we can meet next time.',
                 'author': 'user@mail.com',
                 },
                {'huddleName': groupFixtures[0]['huddleName'],
                 'groupName': groupFixtures[0]['groupName'],
                 'timestamp': datetime(2014,4,1,13,0,35),
                 'text':'Maybe Monday evening?',
                 'author': 'tester@mail.com',
                 },
                {'huddleName': groupFixtures[0]['huddleName'],
                 'groupName': groupFixtures[0]['groupName'],
                 'timestamp': datetime(2014,4,1,13,0,40),
                 'text':'Monday is not good for me, what about Thuesday at 9am?',
                 'author': 'user@mail.com',
                 },
                {'huddleName': groupFixtures[0]['huddleName'],
                 'groupName': groupFixtures[0]['groupName'],
                 'timestamp': datetime(2014,4,1,13,0,45),
                 'text':'Thuesday sounds good, see you then',
                 'author': 'tester@mail.com',
                 },
                {'huddleName': groupFixtures[0]['huddleName'],
                 'groupName': groupFixtures[0]['groupName'],
                 'timestamp': datetime(2014,4,1,13,0,50),
                 'text':'Cool, see you.',
                 'author': 'user@mail.com',
                 },
                ]